apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: loan-origination-listener
  namespace: loan-origination-ci
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push
      bindings:
        - ref: loan-origination-push-binding
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
          params:
            - name: secretRef
              value:
                secretName: github-webhook-secret
                secretKey: webhook-secret
            - name: eventTypes
              value: [push]
        - ref:
            name: cel
            kind: ClusterInterceptor
          params:
            - name: filter
              value: "body.ref == 'refs/heads/main'"
      template:
        ref: loan-origination-deploy-template
